const SUPABASE_URL='https://qwhpikyxilzwazeneddw.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_FjocCd5CH-v6Un0Qg_HBdQ_ujxKhD9q';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const KX_AUTH_URL=`${SUPABASE_URL}/functions/v1/kx-auth`;
async function kxAuth(action, username, password, name=''){const r=await fetch(KX_AUTH_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY},body:JSON.stringify({action,username,password,name})});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Não foi possível concluir a autenticação.');return data}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let user=null,profile=null,activeFeed='for_you',activeCommentPost=null;
const demoMangas=[
{id:'demo-hz',title:'Horizonte Zero',author:'Kairox',genres:'Ação · Fantasia',desc:'Uma jornada começa quando o horizonte deixa de ser o fim.',cover:'c1',rating:'4.8',chapter:'Capítulo 1'},
{id:'demo-tuk',title:'Tuketon',author:'Kairox Studio',genres:'Aventura · Shonen',desc:'Um mundo de reinos, selos e energia INKRA.',cover:'c2',rating:'4.7',chapter:'Capítulo 1'},
{id:'demo-ecl',title:'Eclipse',author:'LinkStory',genres:'Drama · Mistério',desc:'Quando a noite cobre tudo, algumas verdades começam a aparecer.',cover:'c3',rating:'4.6',chapter:'Capítulo 1'},
{id:'demo-cri',title:'Lâmina de Crimson',author:'Hayato Minase',genres:'Ação · Sobrenatural',desc:'Uma lâmina, um juramento e uma guerra que ainda não terminou.',cover:'c4',rating:'4.8',chapter:'Capítulo 3'},
{id:'demo-chu',title:'Depois da Chuva',author:'LinkStory',genres:'Romance · Slice of life',desc:'Algumas histórias começam justamente quando a chuva termina.',cover:'c5',rating:'4.4',chapter:'Capítulo 2'},
{id:'demo-aurea',title:'Áurea',author:'Kairox',genres:'Fantasia · Aventura',desc:'Um reino dourado guarda um segredo que ninguém deveria tocar.',cover:'c6',rating:'4.5',chapter:'Capítulo 1'},
{id:'demo-lua',title:'Última Lua',author:'LinkStory',genres:'Drama · Ação',desc:'O último brilho antes do silêncio.',cover:'c7',rating:'4.3',chapter:'Capítulo 1'}];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(id){const current=document.querySelector('.screen.active');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.target===id));if(current&&current.id!==id){current.classList.remove('screen-enter');void current.offsetWidth;current.classList.add('screen-leave');setTimeout(()=>current.classList.remove('screen-leave'),260)}$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));const next=$('#'+id);if(next){next.classList.remove('screen-enter');void next.offsetWidth;next.classList.add('screen-enter');setTimeout(()=>next.classList.remove('screen-enter'),420)}scrollTo(0,0);if(id==='feed')loadFeed();if(id==='notifications')loadNotifications();if(id==='profile')renderProfile()}
$$('.nav').forEach(n=>n.onclick=()=>nav(n.dataset.target));$('#homeBrand').onclick=()=>nav('home');
function closeModals(){$$('.modal').forEach(m=>m.classList.add('hidden'))}$$('[data-close]').forEach(x=>x.onclick=closeModals);
function taste(){try{return JSON.parse(localStorage.getItem('linkstory_taste')||'{}')}catch{return {}}}
function rememberGenre(genres){const t=taste();String(genres||'').split(/[·,]/).map(x=>x.trim().toLowerCase()).filter(Boolean).forEach(g=>t[g]=(t[g]||0)+1);localStorage.setItem('linkstory_taste',JSON.stringify(t))}
function recommendMangas(list){const t=taste();return [...list].sort((a,b)=>{const score=m=>String(m.genres||'').split(/[·,]/).reduce((s,g)=>s+(t[g.trim().toLowerCase()]||0),0);return score(b)-score(a)})}
function renderMangas(list=demoMangas){const card=m=>`<button class="manga-card" data-manga="${esc(m.id)}"><div class="cover ${m.cover||'c1'}" ${m.cover_url?`style="background-image:url('${esc(m.cover_url)}')"`:''}><span>${esc(String(m.title||'?').slice(0,1))}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.genres||'Mangá')}</p></button>`;const rec=recommendMangas(list);$('#trending').innerHTML=rec.slice(0,4).map(card).join('');$('#newManga').innerHTML=rec.slice(4).map(card).join('');$$('[data-manga]').forEach(b=>b.onclick=()=>openManga(b.dataset.manga))}
async function loadCatalog(){const r=await sb.from('mangas').select('id,title,description,genres,cover_url,created_at,profiles(display_name,username)').eq('status','published').order('created_at',{ascending:false}).limit(30);if(!r.error&&r.data?.length){const list=r.data.map((m,i)=>({id:m.id,title:m.title,author:m.profiles?.display_name||m.profiles?.username||'Criador',genres:m.genres||'Mangá',desc:m.description||'',cover_url:m.cover_url,cover:'c'+((i%7)+1),rating:'',chapter:'Capítulo 1'}));renderMangas([...list,...demoMangas])}else renderMangas()}
async function openManga(id){let m=demoMangas.find(x=>x.id===id);if(!m){const r=await sb.from('mangas').select('id,title,description,genres,cover_url,profiles(display_name,username)').eq('id',id).maybeSingle();if(r.error||!r.data)return;const x=r.data;m={id:x.id,title:x.title,author:x.profiles?.display_name||x.profiles?.username||'Criador',genres:x.genres||'Mangá',desc:x.description||'',cover_url:x.cover_url,cover:'c1',rating:'',chapter:'Capítulo 1'}}rememberGenre(m.genres);$$('[data-manga]').forEach(x=>x.classList.remove('manga-tap'));const source=document.querySelector(`[data-manga="${CSS.escape(id)}"]`);if(source){source.classList.add('manga-tap');setTimeout(()=>source.classList.remove('manga-tap'),420)}$('#mangaDetails').innerHTML=`<div class="detail-cover cover ${m.cover}" ${m.cover_url?`style="background-image:url('${esc(m.cover_url)}')"`:''}><span>${esc(String(m.title).slice(0,1))}</span></div><h2>${esc(m.title)}</h2><p class="muted">por ${esc(m.author)}</p><div class="chips">${String(m.genres||'Mangá').split(/[·,]/).filter(Boolean).map(g=>`<span>${esc(g.trim())}</span>`).join('')}</div><p class="detail-desc">${esc(m.desc)}</p><div id="chapterList" class="chapter-list"><span class="muted">Carregando capítulos...</span></div>`;$('#mangaDetailsModal').classList.remove('hidden');const cr=await sb.from('manga_chapters').select('id,chapter_number,title,created_at').eq('manga_id',m.id).order('chapter_number',{ascending:true});const chapters=cr.data||[];$('#chapterList').innerHTML=chapters.length?chapters.map(c=>`<button class="chapter-item" data-chapter="${c.id}"><b>Capítulo ${esc(c.chapter_number)}</b><span>${esc(c.title)}</span></button>`).join(''):'<p class="muted">O criador ainda não publicou capítulos.</p>';$$('[data-chapter]').forEach(b=>b.onclick=()=>openChapter(b.dataset.chapter,m.title))}
async function openChapter(chapterId,title){const r=await sb.from('manga_pages').select('page_number,image_url').eq('chapter_id',chapterId).order('page_number',{ascending:true});const pages=r.data||[];$('#mangaDetails').innerHTML=`<div class="reader"><span class="eyebrow">LINKSTORY • LEITOR</span><h2>${esc(title)}</h2>${pages.length?pages.map(p=>`<img class="reader-page-img" src="${esc(p.image_url)}" alt="Página ${p.page_number}" loading="lazy">`).join(''):'<div class="reader-page"><b>CAPÍTULO</b><p>Este capítulo ainda não possui páginas.</p></div>'}<button class="outline full" onclick="closeModals()">Fechar leitor</button></div>`}
function kxEmail(username){return `${username.toLowerCase()}@kx.mail`}
function auth(mode='login'){const reg=mode==='register';$('#authContent').innerHTML=`<h2>${reg?'Criar conta LinkStory':'Entrar no LinkStory'}</h2><p class="muted">Escolha seu tipo de conta. <b>Leitor</b> lê e interage; <b>Criador</b> publica mangás e capítulos.</p>${reg?'<input id="nameI" maxlength="60" placeholder="Nome público"><input id="userI" maxlength="24" autocomplete="username" placeholder="Kx ID (ex.: tayan)"><div class="role-choice"><button type="button" class="role-option selected" data-role="leitor"><b>📚 Leitor</b><span>Ler, seguir criadores e publicar no Feed.</span></button><button type="button" class="role-option" data-role="criador"><b>✍️ Criador</b><span>Publicar mangás, capítulos, vídeos e ideias.</span></button></div>':''}<input id="emailI" type="text" autocomplete="username" placeholder="Kx ID ou @usuario.kx.mail"><input id="passI" type="password" autocomplete="current-password" placeholder="Senha (mín. 6 caracteres)"><button class="primary full" id="authSubmit">${reg?'Criar conta':'Entrar'}</button><button class="text-btn" id="authSwitch">${reg?'Já tenho uma conta':'Criar uma conta'}</button>`;$('#authModal').classList.remove('hidden');$$('.role-option').forEach(b=>b.onclick=()=>{$$('.role-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('#authSubmit').onclick=()=>submitAuth(reg);$('#authSwitch').onclick=()=>auth(reg?'login':'register')}
async function submitAuth(register){const password=$('#passI').value.trim();if(!password)return toast('Digite sua senha.');if(password.length<6)return toast('A senha precisa ter pelo menos 6 caracteres.');const usernameRaw=register?$('#userI').value:$('#emailI').value;const username=usernameRaw.trim().replace(/^@/,'').replace(/\.kx\.mail$/i,'').toLowerCase().replace(/[^a-z0-9._-]/g,'');if(!username)return toast('Digite seu Kx ID.');if(username.length<3)return toast('Kx ID muito curto.');try{let chosenRole='leitor';if(register){const name=$('#nameI').value.trim();if(!name)return toast('Preencha seu nome público.');chosenRole=document.querySelector('.role-option.selected')?.dataset.role||'leitor';await kxAuth('signup',username,password,name);toast('Conta criada! Entrando...')}const result=await kxAuth('login',username,password);if(!result.session?.access_token||!result.session?.refresh_token)throw new Error('A sessão não pôde ser criada.');const session=await sb.auth.setSession({access_token:result.session.access_token,refresh_token:result.session.refresh_token});if(session.error)throw session.error;user=session.data.session?.user||null;await loadProfile();if(register&&user){const rr=await sb.from('profiles').update({role:chosenRole}).eq('id',user.id);if(rr.error)throw rr.error;await loadProfile()}closeModals();renderProfile();await loadFeed();if(!register)toast('Login realizado!')}catch(e){toast(e.message||'Não foi possível entrar.')}}
async function logout(){await sb.auth.signOut();user=null;profile=null;renderProfile();toast('Você saiu da conta.')}
async function loadProfile(){if(!user){profile=null;return}const r=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=r.data||null}
function isCreator(){return profile?.role==='criador'}
function requireCreator(){if(!user){auth('login');return false}if(!isCreator()){toast('Esta função é exclusiva para contas Criador.');return false}return true}
function applyRoleUI(){const creator=isCreator();$$('.creator-only').forEach(el=>el.classList.toggle('role-hidden',!creator));if($('#createRoleHint'))$('#createRoleHint').textContent=creator?'Modo Criador: publique e gerencie seus mangás.':'Modo Leitor: explore histórias, siga criadores e publique fotos/vídeos no Feed.'}
function avatarHTML(url,name,cls='avatar'){return url?`<img class="${cls} avatar-img" src="${esc(url)}" alt="Avatar de ${esc(name||'usuário')}">`:`<div class="${cls}">${esc((name||'?').slice(0,2).toUpperCase())}</div>`}
async function openSettings(){if(!user)return auth('login');if(!profile)await loadProfile();$('#settingsName').value=profile?.display_name||user.user_metadata?.display_name||'';$('#settingsUsername').value=profile?.username||'';$('#settingsRecovery').value=profile?.recovery_email||'';$('#settingsModal').classList.remove('hidden')}
if($('#settingsBtn'))$('#settingsBtn').onclick=openSettings;$('#profileMenuTop').onclick=()=>user?openSettings():auth('login');$('#clearTasteBtn').onclick=()=>{localStorage.removeItem('linkstory_taste');toast('Preferências de gosto limpas.')};
$('#saveSettingsBtn').onclick=async()=>{if(!user)return auth('login');const display_name=$('#settingsName').value.trim();const recovery_email=$('#settingsRecovery').value.trim();if(!display_name)return toast('Digite seu nome público.');if(recovery_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recovery_email))return toast('Digite um e-mail válido ou deixe em branco.');const r=await sb.from('profiles').update({display_name,recovery_email:recovery_email||null}).eq('id',user.id);if(r.error)return toast('Não foi possível salvar: '+r.error.message);await loadProfile();closeModals();renderProfile();toast('Configurações salvas.')};
async function openEditProfile(){if(!user)return auth('login');await loadProfile();$('#editProfileName').value=profile?.display_name||'';$('#editProfileBio').value=profile?.bio||'';$('#editAvatarFile').value='';$('#editProfileModal').classList.remove('hidden')}
async function uploadFile(file,folder){if(!file)return null;const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${user.id}/${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const r=await sb.storage.from('linkstory-media').upload(path,file,{upsert:false,contentType:file.type||undefined});if(r.error)throw r.error;return sb.storage.from('linkstory-media').getPublicUrl(path).data.publicUrl}
$('#saveProfileBtn').onclick=async()=>{if(!user)return auth('login');try{const display_name=$('#editProfileName').value.trim();const bio=$('#editProfileBio').value.trim();if(!display_name)return toast('Coloque seu nome público.');let avatar_url=profile?.avatar_url||null;const file=$('#editAvatarFile').files[0];if(file)avatar_url=await uploadFile(file,'avatars');const r=await sb.from('profiles').update({display_name,bio,avatar_url}).eq('id',user.id);if(r.error)throw r.error;await loadProfile();closeModals();renderProfile();toast('Perfil atualizado!')}catch(e){toast(e.message||'Não foi possível atualizar o perfil.')}};
async function renderProfile(){if(!user){$('#profileName').textContent='Seu perfil';$('#profileTopHandle').textContent='@seuusuario';$('#profileHandle').textContent='@seuusuario · Visitante';$('#profileBio').textContent='Crie sua conta para publicar e acompanhar criadores.';$('#profileAvatar').innerHTML='?';$('#profileRoleBadge').textContent='';$('#profileActions').innerHTML='<button class="primary full" id="registerBtn">Criar minha conta</button>';$('#registerBtn').onclick=()=>auth('register');$('#statPosts').textContent='0';$('#statFollowers').textContent='0';$('#statFollowing').textContent='0';$('#profileGrid').innerHTML='';$('#profileStories').innerHTML='';applyRoleUI();return}if(!profile)await loadProfile();const name=profile?.display_name||user.user_metadata?.display_name||'Usuário';const handle=profile?.username||'usuario';$('#profileName').textContent=name;$('#profileTopHandle').textContent='@'+handle;$('#profileHandle').textContent='@'+handle+'.kx.mail';$('#profileBio').textContent=profile?.bio||'Sem bio ainda.';$('#profileRoleBadge').textContent=isCreator()?'CRIADOR':'LEITOR';const pref=profile?.preferences||{};$('#profileAvatar').innerHTML=profile?.avatar_url?`<img class="avatar-img profile-avatar-img" src="${esc(profile.avatar_url)}" alt="Foto de perfil">`:esc(name.slice(0,2).toUpperCase());const [posts,followers,following,grid,mangas,stories]=await Promise.all([sb.from('posts').select('id',{count:'exact',head:true}).eq('author_id',user.id).neq('post_type','story'),sb.from('follows').select('follower_id',{count:'exact',head:true}).eq('following_id',user.id),sb.from('follows').select('following_id',{count:'exact',head:true}).eq('follower_id',user.id),sb.from('posts').select('id,body,post_type,media_url,media_type,thumbnail_url,created_at').eq('author_id',user.id).neq('post_type','story').order('created_at',{ascending:false}).limit(60),sb.from('mangas').select('id,title,description,cover_url,genres,created_at').eq('creator_id',user.id).order('created_at',{ascending:false}).limit(30),sb.from('posts').select('id,body,post_type,media_url,media_type,created_at').eq('author_id',user.id).eq('post_type','story').gte('created_at',new Date(Date.now()-86400000).toISOString()).order('created_at',{ascending:false}).limit(12)]);$('#statPosts').textContent=posts.count||0;$('#statFollowers').textContent=followers.count||0;$('#statFollowing').textContent=following.count||0;$('#profileActions').innerHTML='<button class="outline full" id="editProfileBtn2">Editar perfil</button><button class="outline full" id="roleBtn">Mudar tipo de conta</button>';$('#editProfileBtn2').onclick=openEditProfile;$('#roleBtn').onclick=()=>chooseRole();profilePostsCache=grid.data||[];profileMangasCache=mangas.data||[];renderProfileTab(activeProfileTab);renderProfileStories([...(stories.data||[])]);renderCreatorMangas(profileMangasCache);applyRoleUI()}
let profilePostsCache=[],profileMangasCache=[],activeProfileTab='posts';
function renderProfileTab(tab){activeProfileTab=tab;$$('.profile-tab').forEach(b=>b.classList.toggle('active',b.dataset.profileTab===tab));const box=$('#profileGrid');if(tab==='mangas'){if(!isCreator())return box.innerHTML='<div class="empty-state">Mangás são exclusivos de contas Criador.</div>';box.innerHTML=profileMangasCache.length?profileMangasCache.map(m=>`<button class="profile-grid-item manga-grid-item" data-open-manga="${esc(m.id)}"><span>▱</span><b>${esc(m.title)}</b></button>`).join(''):'<div class="empty-state">Você ainda não criou nenhum mangá.</div>';$$('[data-open-manga]').forEach(b=>b.onclick=()=>openManga(b.dataset.openManga));return}const items=profilePostsCache.filter(p=>tab==='videos'?p.media_type==='video':p.media_type!=='video');box.innerHTML=items.length?items.map(p=>p.media_type==='video'?`<button class="profile-grid-item" data-grid-post="${p.id}"><video src="${esc(p.media_url)}" muted preload="metadata"></video><span>▶</span></button>`:p.media_url?`<button class="profile-grid-item" data-grid-post="${p.id}"><img src="${esc(p.media_url)}" alt="Publicação"></button>`:`<button class="profile-grid-item text-grid" data-grid-post="${p.id}">${esc((p.body||'').slice(0,90))}</button>`).join(''):'<div class="empty-state">Nenhuma publicação nesta aba.</div>';$$('[data-grid-post]').forEach(b=>b.onclick=()=>openProfilePost(b.dataset.gridPost))}
async function openProfilePost(id){const p=profilePostsCache.find(x=>x.id===id);if(!p)return;nav('feed');setTimeout(()=>{const el=document.querySelector(`[data-post-id="${CSS.escape(id)}"]`);el?.scrollIntoView({behavior:'smooth',block:'center'})},120)}
function renderProfileStories(items){const box=$('#profileStories');const own=items.filter(x=>x.post_type==='story').slice(0,6);box.innerHTML=`<button class="story-bubble" id="profileAddStory"><div class="story-ring"><span>＋</span></div><small>Novo</small></button>`+own.map(x=>`<button class="story-bubble" data-profile-story="${esc(x.id)}"><div class="story-ring">${x.media_url?`<img src="${esc(x.media_url)}">`:'<div class="story-placeholder">S</div>'}</div><small>Meus</small></button>`).join('');$('#profileAddStory').onclick=()=>openStoryComposer();$$('[data-profile-story]').forEach(b=>b.onclick=()=>{const st=own.find(x=>x.id===b.dataset.profileStory);if(st)openStory(st)})}
function openStory(st){$('#storyViewer').innerHTML=`<div class="story-full">${st.media_url?`<img src="${esc(st.media_url)}" alt="Story">`:''}<div class="story-full-caption">${esc(st.body||'')}</div><small>${new Date(st.created_at).toLocaleString('pt-BR')}</small></div>`;$('#storyViewerModal').classList.remove('hidden')}
let storySelectedFile=null;function openStoryEditor(file){if(!file||!file.type.startsWith('image/'))return toast('Escolha uma imagem válida.');storySelectedFile=file;$('#storyPreview').src=URL.createObjectURL(file);$('#storyStart').classList.add('hidden');$('#storyEditor').classList.remove('hidden')}$('#storyCameraBtn').onclick=()=>$('#storyCameraFile').click();$('#storyGalleryBtn').onclick=()=>$('#storyGalleryFile').click();$('#storyCameraFile').onchange=e=>openStoryEditor(e.target.files[0]);$('#storyGalleryFile').onchange=e=>openStoryEditor(e.target.files[0]);$('#storyChangeBtn').onclick=()=>{$('#storyStart').classList.remove('hidden');$('#storyEditor').classList.add('hidden')};$('#publishStoryBtn').onclick=async()=>{if(!user)return auth('login');try{const file=storySelectedFile,body=$('#storyText').value.trim();if(!file)return toast('Escolha uma foto para o story.');const media_url=await uploadFile(file,'stories');const r=await sb.from('posts').insert({author_id:user.id,body:body||'',post_type:'story',media_url,media_type:'image'});if(r.error)throw r.error;storySelectedFile=null;$('#storyCameraFile').value='';$('#storyGalleryFile').value='';$('#storyText').value='';closeModals();await loadStories();await renderProfile();toast('Story publicado por 24h!')}catch(e){toast(e.message||'Não foi possível publicar o story.')}};
const _loadFeed=loadFeed;loadFeed=async function(){await _loadFeed();await loadStories()};

$('#publishVideoBtn').onclick=async()=>{if(!user)return auth('login');try{const body=$('#videoText').value.trim(),file=$('#videoFile').files[0];if(!file||!file.type.startsWith('video/'))return toast('Escolha um vídeo.');if(file.size>50*1024*1024)return toast('O vídeo precisa ter até 50 MB.');const media_url=await uploadFile(file,'videos');const r=await sb.from('posts').insert({author_id:user.id,body,post_type:'video',media_url,media_type:'video'});if(r.error)throw r.error;$('#videoText').value='';$('#videoFile').value='';closeModals();nav('feed');toast('Vídeo publicado no Feed! 🎬')}catch(e){toast(e.message||'Não foi possível publicar o vídeo.')}};
$('#mangaCreate').onclick=()=>{if(!requireCreator())return;$('#mangaModal').classList.remove('hidden')};$('#videoCreate').onclick=()=>{if(!user)return auth('login');$('#videoModal').classList.remove('hidden')};$('#ideaCreate').onclick=()=>{if(!user)return auth('login');$('#ideaModal').classList.remove('hidden')};
$('#authBtn').onclick=()=>user?logout():auth('login');$('#registerBtn').onclick=()=>auth('register');$('#readBtn').onclick=()=>nav('feed');$('#feedRefresh').onclick=()=>loadFeed();
$$('[data-feed]').forEach(b=>b.onclick=()=>{activeFeed=b.dataset.feed;$$('[data-feed]').forEach(x=>x.classList.toggle('active',x===b));loadFeed()});
$$('[data-browse]').forEach(b=>b.onclick=()=>{nav('feed');toast('Catálogo aberto no Feed por enquanto.')});
$('#searchBtn').onclick=()=>{$('#searchModal').classList.remove('hidden');$('#searchInput').focus();renderSearch('')};$('#searchInput').oninput=e=>renderSearch(e.target.value);
function renderSearch(q){const term=q.trim().toLowerCase();const ms=demoMangas.filter(m=>!term||[m.title,m.author,m.genres].join(' ').toLowerCase().includes(term));$('#searchResults').innerHTML=ms.map(m=>`<button class="search-item" data-search-manga="${m.id}"><div class="mini-cover cover ${m.cover}">${esc(m.title[0])}</div><div><b>${esc(m.title)}</b><small>${esc(m.author)} · ${esc(m.genres)}</small></div></button>`).join('')||'<p class="muted">Nada encontrado.</p>';$$('[data-search-manga]').forEach(b=>b.onclick=()=>{closeModals();openManga(b.dataset.searchManga)})}
async function loadNotifications(){const box=$('#noticeList');if(!user){box.innerHTML='<div class="empty-state">Entre na sua conta para ver seus avisos.</div>';return}const r=await sb.from('notifications').select('id,type,post_id,read_at,created_at,actor_id').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30);if(r.error){box.innerHTML='<div class="empty-state">Não foi possível carregar os avisos.</div>';return}box.innerHTML=(r.data||[]).map(n=>`<div class="notice ${n.read_at?'':'unread'}"><div class="avatar gold">${n.type==='like'?'♥':n.type==='comment'?'💬':n.type==='follow'?'＋':'•'}</div><p>${noticeText(n.type)}<small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></p></div>`).join('')||'<div class="empty-state">Nenhum aviso ainda.</div>'}
function noticeText(type){return ({like:'Alguém curtiu sua publicação.',comment:'Alguém comentou na sua publicação.',follow:'Alguém começou a seguir você.'}[type]||'Você tem uma nova atividade no LinkStory.')}
$('#readNotices').onclick=async()=>{if(!user)return auth('login');await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);loadNotifications();toast('Avisos marcados como lidos.')};
sb.auth.onAuthStateChange(async(_event,session)=>{user=session?.user||null;await loadProfile();renderProfile();if($('#feed').classList.contains('active'))loadFeed()});
(async()=>{const s=await sb.auth.getSession();user=s.data.session?.user||null;await loadProfile();applyRoleUI();await loadCatalog();renderProfile();loadFeed()})();

$$('[data-profile-tab]').forEach(b=>b.onclick=()=>renderProfileTab(b.dataset.profileTab));
let cropSourceFile=null,cropObjectUrl=null;
function openAvatarCrop(){const f=$('#editAvatarFile').files[0];if(!f){toast('Escolha uma foto primeiro.');return}cropSourceFile=f;if(cropObjectUrl)URL.revokeObjectURL(cropObjectUrl);cropObjectUrl=URL.createObjectURL(f);$('#cropImage').src=cropObjectUrl;$('#cropZoom').value=1;$('#cropX').value=50;$('#cropY').value=50;updateCropPreview();$('#avatarCropModal').classList.remove('hidden')}
function updateCropPreview(){const img=$('#cropImage');if(!img)return;img.style.transform=`scale(${$('#cropZoom').value})`;img.style.objectPosition=`${$('#cropX').value}% ${$('#cropY').value}%`}
$('#avatarCropOpen').onclick=openAvatarCrop;$('#editAvatarFile').onchange=()=>{if($('#editAvatarFile').files[0])openAvatarCrop()};['cropZoom','cropX','cropY'].forEach(id=>$('#'+id).oninput=updateCropPreview);
async function cropAvatarToBlob(file,zoom,x,y){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const size=640,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');const scale=Math.max(size/img.width,size/img.height)*zoom;const dw=img.width*scale,dh=img.height*scale;const maxX=Math.max(0,dw-size),maxY=Math.max(0,dh-size);const dx=-(x/100)*maxX,dy=-(y/100)*maxY;ctx.fillStyle='#111';ctx.fillRect(0,0,size,size);ctx.drawImage(img,dx,dy,dw,dh);canvas.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve(blob):reject(new Error('Não foi possível recortar a foto.'))},'image/jpeg',.92)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível ler a foto.'))};img.src=url})}
$('#cropConfirmBtn').onclick=async()=>{if(!cropSourceFile)return;try{const blob=await cropAvatarToBlob(cropSourceFile,Number($('#cropZoom').value),Number($('#cropX').value),Number($('#cropY').value));const cropped=new File([blob],'avatar.jpg',{type:'image/jpeg'});const dt=new DataTransfer();dt.items.add(cropped);$('#editAvatarFile').files=dt.files;$('#avatarCropThumb').innerHTML=`<img src="${URL.createObjectURL(blob)}" alt="Prévia">`;closeModals();$('#editProfileModal').classList.remove('hidden');toast('Enquadramento aplicado. Clique em Salvar perfil.')}catch(e){toast(e.message)}};

/* LINKSTORY_PROFILE_FIX_V2 */
(()=>{
  const profilePostState={activeTab:'posts'};
  function profilePostFromEl(el){
    const host=el.closest('[data-profile-post],[data-post],.profile-post,.profile-grid-item,.profile-card');
    if(!host)return null;
    const id=host.dataset.profilePost||host.dataset.post||host.dataset.id||host.getAttribute('data-profile-post');
    return {host,id};
  }
  function openOwnProfilePost(id,host){
    if(!id)return;
    if(typeof window.openPost==='function'){window.openPost(id);return;}
    if(typeof window.openPostViewer==='function'){window.openPostViewer(id);return;}
    if(typeof window.viewPost==='function'){window.viewPost(id);return;}
    if(typeof window.openFeedPost==='function'){window.openFeedPost(id);return;}
    const media=host?.querySelector('img,video');
    if(media){
      const src=media.currentSrc||media.src;
      const viewer=document.createElement('div');
      viewer.className='modal profile-media-viewer';
      viewer.innerHTML=`<div class="modal-box wide profile-media-box"><button class="close" type="button">×</button>${media.tagName==='VIDEO'?`<video controls autoplay class="profile-media-full" src="${esc(src)}"></video>`:`<img class="profile-media-full" src="${esc(src)}" alt="Publicação do perfil">`}<div class="muted profile-media-note">Publicação do seu perfil</div></div>`;
      document.body.appendChild(viewer);
      viewer.querySelector('.close').onclick=()=>viewer.remove();
      viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.remove()});
    }
  }
  document.addEventListener('click',e=>{
    const profileGrid=document.querySelector('#profileGrid');
    if(profileGrid && profileGrid.contains(e.target)){
      const found=profilePostFromEl(e.target);
      if(found){e.preventDefault();e.stopImmediatePropagation();openOwnProfilePost(found.id,found.host);return;}
    }
    const following=e.target.closest('#statFollowing, [data-profile-tab="following"], [data-profile-stat="following"], .stat-following');
    if(following && document.querySelector('#profile')){
      e.preventDefault();e.stopImmediatePropagation();
      if(typeof window.openFollowing==='function'){window.openFollowing();return;}
      if(typeof window.loadFollowing==='function'){window.loadFollowing();return;}
      if(typeof window.showFollowing==='function'){window.showFollowing();return;}
      const current=document.querySelector('#profileFollowingModal');
      if(current){current.classList.remove('hidden');return;}
      const box=document.createElement('div');box.className='modal profile-following-fallback';box.innerHTML='<div class="modal-box"><button class="close" type="button">×</button><span class="eyebrow">SUA REDE</span><h2>Seguindo</h2><p class="muted">Aqui aparecerão as pessoas que você segue. Ainda não há ninguém para mostrar.</p><button class="primary full" type="button">Explorar criadores</button></div>';document.body.appendChild(box);const close=()=>box.remove();box.querySelector('.close').onclick=close;box.querySelector('.primary').onclick=()=>{close();typeof window.nav==='function'&&window.nav('feed')};
    }
  },true);
  const style=document.createElement('style');
  style.textContent='.profile-media-viewer{z-index:9999}.profile-media-box{max-height:90vh;overflow:auto}.profile-media-full{display:block;width:100%;max-height:70vh;object-fit:contain;border-radius:14px}.profile-media-note{padding-top:10px}.profile-following-fallback{z-index:9998}.profile-following-fallback .modal-box{max-width:420px}';
  document.head.appendChild(style);
})();
