const SUPABASE_URL='https://qwhpikyxilzwazeneddw.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_FjocCd5CH-v6Un0Qg_HBdQ_ujxKhD9q';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const KX_AUTH_URL=`${SUPABASE_URL}/functions/v1/kx-auth`;
async function kxAuth(action, username, password, name=''){const r=await fetch(KX_AUTH_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY},body:JSON.stringify({action,username,password,name})});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Não foi possível concluir a autenticação.');return data}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let user=null,profile=null,activeFeed='for_you',activeCommentPost=null;
const demoMangas=[
{id:'demo-hz',title:'Horizonte Zero',author:'Kairox',genres:'Ação · Fantasia',desc:'Uma jornada começa quando o horizonte deixa de ser o fim.',cover:'c1',rating:'4.8',chapter:'Capítulo 1'},
{id:'demo-tuk',title:'Tuketon',author:'Kairox Studio',genres:'Aventura · Shonen',desc:'Um mundo de reinos, selos e energia INKRA.',cover:'c2',rating:'4.7',chapter:'Capítulo 1'},
{id:'demo-ecl',title:'Eclipse',author:'LinkStory',genres:'Drama · Mistério',desc:'Quando a noite cobre tudo, algumas verdades começam a aparecer.',cover:'c3',rating:'4.6',chapter:'Capítulo 1'},
{id:'demo-cri',title:'Lâmina de Crimson',author:'Hayato Minase',genres:'Ação · Sobrenatural',desc:'Uma lâmina, um juramento e uma guerra que ainda não terminou.',cover:'c4',rating:'4.8',chapter:'Capítulo 3'},
{id:'demo-chu',title:'Depois da Chuva',author:'LinkStory',genres:'Romance · Slice of life',desc:'Algumas histórias começam justamente quando a chuva termina.',cover:'c5',rating:'4.4',chapter:'Capítulo 2'},
{id:'demo-aurea',title:'Áurea',author:'Kairox',genres:'Fantasia · Aventura',desc:'Um reino dourado guarda um segredo que ninguém deveria tocar.',cover:'c6',rating:'4.5',chapter:'Capítulo 1'},
{id:'demo-lua',title:'Última Lua',author:'LinkStory',genres:'Drama · Ação',desc:'O último brilho antes do silêncio.',cover:'c7',rating:'4.3',chapter:'Capítulo 1'}];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(id){const current=document.querySelector('.screen.active');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.target===id));if(current&&current.id!==id){current.classList.remove('screen-enter');void current.offsetWidth;current.classList.add('screen-leave');setTimeout(()=>current.classList.remove('screen-leave'),260)}$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));const next=$('#'+id);if(next){next.classList.remove('screen-enter');void next.offsetWidth;next.classList.add('screen-enter');setTimeout(()=>next.classList.remove('screen-enter'),420)}scrollTo(0,0);if(id==='feed')loadFeed();if(id==='notifications')loadNotifications();if(id==='profile')renderProfile()}
$$('.nav').forEach(n=>n.onclick=()=>nav(n.dataset.target));$('#homeBrand').onclick=()=>nav('home');
function closeModals(){$$('.modal').forEach(m=>m.classList.add('hidden'))}$$('[data-close]').forEach(x=>x.onclick=closeModals);
function taste(){try{return JSON.parse(localStorage.getItem('linkstory_taste')||'{}')}catch{return {}}}
function rememberGenre(genres){const t=taste();String(genres||'').split(/[·,]/).map(x=>x.trim().toLowerCase()).filter(Boolean).forEach(g=>t[g]=(t[g]||0)+1);localStorage.setItem('linkstory_taste',JSON.stringify(t))}
function recommendMangas(list){const t=taste();return [...list].sort((a,b)=>{const score=m=>String(m.genres||'').split(/[·,]/).reduce((s,g)=>s+(t[g.trim().toLowerCase()]||0),0);return score(b)-score(a)})}
function renderMangas(list=demoMangas){const card=m=>`<button class="manga-card" data-manga="${esc(m.id)}"><div class="cover ${m.cover||'c1'}" ${m.cover_url?`style="background-image:url('${esc(m.cover_url)}')"`:''}><span>${esc(String(m.title||'?').slice(0,1))}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.genres||'Mangá')}</p></button>`;const rec=recommendMangas(list);$('#trending').innerHTML=rec.slice(0,4).map(card).join('');$('#newManga').innerHTML=rec.slice(4).map(card).join('');$$('[data-manga]').forEach(b=>b.onclick=()=>openManga(b.dataset.manga))}
async function loadCatalog(){const r=await sb.from('mangas').select('id,title,description,genres,cover_url,created_at,profiles(display_name,username)').eq('status','published').order('created_at',{ascending:false}).limit(30);if(!r.error&&r.data?.length){const list=r.data.map((m,i)=>({id:m.id,title:m.title,author:m.profiles?.display_name||m.profiles?.username||'Criador',genres:m.genres||'Mangá',desc:m.description||'',cover_url:m.cover_url,cover:'c'+((i%7)+1),rating:'',chapter:'Capítulo 1'}));renderMangas([...list,...demoMangas])}else renderMangas()}
async function openManga(id){let m=demoMangas.find(x=>x.id===id);if(!m){const r=await sb.from('mangas').select('id,title,description,genres,cover_url,profiles(display_name,username)').eq('id',id).maybeSingle();if(r.error||!r.data)return;const x=r.data;m={id:x.id,title:x.title,author:x.profiles?.display_name||x.profiles?.username||'Criador',genres:x.genres||'Mangá',desc:x.description||'',cover_url:x.cover_url,cover:'c1',rating:'',chapter:'Capítulo 1'}}rememberGenre(m.genres);$$('[data-manga]').forEach(x=>x.classList.remove('manga-tap'));const source=document.querySelector(`[data-manga="${CSS.escape(id)}"]`);if(source){source.classList.add('manga-tap');setTimeout(()=>source.classList.remove('manga-tap'),420)}$('#mangaDetails').innerHTML=`<div class="detail-cover cover ${m.cover}" ${m.cover_url?`style="background-image:url('${esc(m.cover_url)}')"`:''}><span>${esc(String(m.title).slice(0,1))}</span></div><h2>${esc(m.title)}</h2><p class="muted">por ${esc(m.author)}</p><div class="chips">${String(m.genres||'Mangá').split(/[·,]/).filter(Boolean).map(g=>`<span>${esc(g.trim())}</span>`).join('')}</div><p class="detail-desc">${esc(m.desc)}</p><div id="chapterList" class="chapter-list"><span class="muted">Carregando capítulos...</span></div>`;$('#mangaDetailsModal').classList.remove('hidden');const cr=await sb.from('manga_chapters').select('id,chapter_number,title,created_at').eq('manga_id',m.id).order('chapter_number',{ascending:true});const chapters=cr.data||[];$('#chapterList').innerHTML=chapters.length?chapters.map(c=>`<button class="chapter-item" data-chapter="${c.id}"><b>Capítulo ${esc(c.chapter_number)}</b><span>${esc(c.title)}</span></button>`).join(''):'<p class="muted">O criador ainda não publicou capítulos.</p>';$$('[data-chapter]').forEach(b=>b.onclick=()=>openChapter(b.dataset.chapter,m.title))}
async function openChapter(chapterId,title){const r=await sb.from('manga_pages').select('page_number,image_url').eq('chapter_id',chapterId).order('page_number',{ascending:true});const pages=r.data||[];$('#mangaDetails').innerHTML=`<div class="reader"><span class="eyebrow">LINKSTORY • LEITOR</span><h2>${esc(title)}</h2>${pages.length?pages.map(p=>`<img class="reader-page-img" src="${esc(p.image_url)}" alt="Página ${p.page_number}" loading="lazy">`).join(''):'<div class="reader-page"><b>CAPÍTULO</b><p>Este capítulo ainda não possui páginas.</p></div>'}<button class="outline full" onclick="closeModals()">Fechar leitor</button></div>`}
function kxEmail(username){return `${username.toLowerCase()}@kx.mail`}
function auth(mode='login'){const reg=mode==='register';$('#authContent').innerHTML=`<h2>${reg?'Criar conta LinkStory':'Entrar no LinkStory'}</h2><p class="muted">Use seu <b>Kx ID</b> e senha. O sistema transforma automaticamente o Kx ID em <b>@usuario.kx.mail</b>. O Gmail é opcional e fica nas configurações.</p>${reg?'<input id="nameI" maxlength="60" placeholder="Nome público"><input id="userI" maxlength="24" autocomplete="username" placeholder="Kx ID (ex.: tayan)">':''}<input id="emailI" type="text" autocomplete="username" placeholder="Kx ID ou @usuario.kx.mail"><input id="passI" type="password" autocomplete="current-password" placeholder="Senha (mín. 6 caracteres)"><button class="primary full" id="authSubmit">${reg?'Criar conta':'Entrar'}</button><button class="text-btn" id="authSwitch">${reg?'Já tenho uma conta':'Criar uma conta'}</button>`;$('#authModal').classList.remove('hidden');$('#authSubmit').onclick=()=>submitAuth(reg);$('#authSwitch').onclick=()=>auth(reg?'login':'register')}
async function submitAuth(register){const password=$('#passI').value.trim();if(!password)return toast('Digite sua senha.');if(password.length<6)return toast('A senha precisa ter pelo menos 6 caracteres.');const usernameRaw=register?$('#userI').value:$('#emailI').value;const username=usernameRaw.trim().replace(/^@/,'').replace(/\.kx\.mail$/i,'').toLowerCase().replace(/[^a-z0-9._-]/g,'');if(!username)return toast('Digite seu Kx ID.');if(username.length<3)return toast('Kx ID muito curto.');try{if(register){const name=$('#nameI').value.trim();if(!name)return toast('Preencha seu nome público.');await kxAuth('signup',username,password,name);toast('Conta criada! Entrando...')}const result=await kxAuth('login',username,password);if(!result.session?.access_token||!result.session?.refresh_token)throw new Error('A sessão não pôde ser criada.');const session=await sb.auth.setSession({access_token:result.session.access_token,refresh_token:result.session.refresh_token});if(session.error)throw session.error;user=session.data.session?.user||null;await loadProfile();closeModals();renderProfile();await loadFeed();if(!register)toast('Login realizado!')}catch(e){toast(e.message||'Não foi possível entrar.')}}
async function logout(){await sb.auth.signOut();user=null;profile=null;renderProfile();toast('Você saiu da conta.')}
async function loadProfile(){if(!user){profile=null;return}const r=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=r.data||null}
function isCreator(){return profile?.role==='criador'}
function requireCreator(){if(!user){auth('login');return false}if(!isCreator()){toast('Esta função é exclusiva para contas Criador.');return false}return true}
function applyRoleUI(){const creator=isCreator();$$('.creator-only').forEach(el=>el.classList.toggle('role-hidden',!creator));if($('#createRoleHint'))$('#createRoleHint').textContent=creator?'Modo Criador: publique e gerencie seus mangás.':'Modo Leitor: explore histórias, siga criadores e publique fotos/vídeos no Feed.'}
function avatarHTML(url,name,cls='avatar'){return url?`<img class="${cls} avatar-img" src="${esc(url)}" alt="Avatar de ${esc(name||'usuário')}">`:`<div class="${cls}">${esc((name||'?').slice(0,2).toUpperCase())}</div>`}
async function openSettings(){if(!user)return auth('login');if(!profile)await loadProfile();$('#settingsName').value=profile?.display_name||user.user_metadata?.display_name||'';$('#settingsUsername').value=profile?.username||'';$('#settingsRecovery').value=profile?.recovery_email||'';$('#settingsModal').classList.remove('hidden')}
if($('#settingsBtn'))$('#settingsBtn').onclick=openSettings;$('#profileMenuTop').onclick=()=>user?openSettings():auth('login');$('#clearTasteBtn').onclick=()=>{localStorage.removeItem('linkstory_taste');toast('Preferências de gosto limpas.')};
$('#saveSettingsBtn').onclick=async()=>{if(!user)return auth('login');const display_name=$('#settingsName').value.trim();const recovery_email=$('#settingsRecovery').value.trim();if(!display_name)return toast('Digite seu nome público.');if(recovery_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recovery_email))return toast('Digite um e-mail válido ou deixe em branco.');const r=await sb.from('profiles').update({display_name,recovery_email:recovery_email||null}).eq('id',user.id);if(r.error)return toast('Não foi possível salvar: '+r.error.message);await loadProfile();closeModals();renderProfile();toast('Configurações salvas.')};
async function openEditProfile(){if(!user)return auth('login');await loadProfile();$('#editProfileName').value=profile?.display_name||'';$('#editProfileBio').value=profile?.bio||'';$('#editAvatarFile').value='';$('#editProfileModal').classList.remove('hidden')}
async function uploadFile(file,folder){if(!file)return null;const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${user.id}/${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const r=await sb.storage.from('linkstory-media').upload(path,file,{upsert:false,contentType:file.type||undefined});if(r.error)throw r.error;return sb.storage.from('linkstory-media').getPublicUrl(path).data.publicUrl}
$('#saveProfileBtn').onclick=async()=>{if(!user)return auth('login');try{const display_name=$('#editProfileName').value.trim();const bio=$('#editProfileBio').value.trim();if(!display_name)return toast('Coloque seu nome público.');let avatar_url=profile?.avatar_url||null;const file=$('#editAvatarFile').files[0];if(file)avatar_url=await uploadFile(file,'avatars');const r=await sb.from('profiles').update({display_name,bio,avatar_url}).eq('id',user.id);if(r.error)throw r.error;await loadProfile();closeModals();renderProfile();toast('Perfil atualizado!')}catch(e){toast(e.message||'Não foi possível atualizar o perfil.')}};
async function renderProfile(){if(!user){$('#profileName').textContent='Seu perfil';$('#profileTopHandle').textContent='@seuusuario';$('#profileHandle').textContent='@seuusuario · Visitante';$('#profileBio').textContent='Crie sua conta para publicar e acompanhar criadores.';$('#profileAvatar').innerHTML='?';$('#profileRoleBadge').textContent='';$('#profileActions').innerHTML='<button class="primary full" id="registerBtn">Criar minha conta</button>';$('#registerBtn').onclick=()=>auth('register');$('#statPosts').textContent='0';$('#statFollowers').textContent='0';$('#statFollowing').textContent='0';$('#profileGrid').innerHTML='';$('#profileStories').innerHTML='';applyRoleUI();return}if(!profile)await loadProfile();const name=profile?.display_name||user.user_metadata?.display_name||'Usuário';const handle=profile?.username||'usuario';$('#profileName').textContent=name;$('#profileTopHandle').textContent='@'+handle;$('#profileHandle').textContent='@'+handle+'.kx.mail';$('#profileBio').textContent=profile?.bio||'Sem bio ainda.';$('#profileRoleBadge').textContent=isCreator()?'CRIADOR':'LEITOR';const pref=profile?.preferences||{};$('#profileAvatar').innerHTML=profile?.avatar_url?`<img class="avatar-img profile-avatar-img" src="${esc(profile.avatar_url)}" alt="Foto de perfil">`:esc(name.slice(0,2).toUpperCase());const [posts,followers,following,grid,mangas,stories]=await Promise.all([sb.from('posts').select('id',{count:'exact',head:true}).eq('author_id',user.id).neq('post_type','story'),sb.from('follows').select('follower_id',{count:'exact',head:true}).eq('following_id',user.id),sb.from('follows').select('following_id',{count:'exact',head:true}).eq('follower_id',user.id),sb.from('posts').select('id,body,post_type,media_url,media_type,thumbnail_url,created_at').eq('author_id',user.id).neq('post_type','story').order('created_at',{ascending:false}).limit(60),sb.from('mangas').select('id,title,description,cover_url,genres,created_at').eq('creator_id',user.id).order('created_at',{ascending:false}).limit(30),sb.from('posts').select('id,body,post_type,media_url,media_type,created_at').eq('author_id',user.id).eq('post_type','story').gte('created_at',new Date(Date.now()-86400000).toISOString()).order('created_at',{ascending:false}).limit(12)]);$('#statPosts').textContent=posts.count||0;$('#statFollowers').textContent=followers.count||0;$('#statFollowing').textContent=following.count||0;$('#profileActions').innerHTML='<button class="outline full" id="editProfileBtn2">Editar perfil</button><button class="outline full" id="roleBtn">Mudar tipo de conta</button>';$('#editProfileBtn2').onclick=openEditProfile;$('#roleBtn').onclick=()=>chooseRole();profilePostsCache=grid.data||[];profileMangasCache=mangas.data||[];renderProfileTab(activeProfileTab);renderProfileStories([...(stories.data||[])]);renderCreatorMangas(profileMangasCache);applyRoleUI()}
let profilePostsCache=[],profileMangasCache=[],activeProfileTab='posts';
function renderProfileTab(tab){activeProfileTab=tab;$$('.profile-tab').forEach(b=>b.classList.toggle('active',b.dataset.profileTab===tab));const box=$('#profileGrid');if(tab==='mangas'){if(!isCreator())return box.innerHTML='<div class="empty-state">Mangás são exclusivos de contas Criador.</div>';box.innerHTML=profileMangasCache.length?profileMangasCache.map(m=>`<button class="profile-grid-item manga-grid-item" data-open-manga="${esc(m.id)}"><span>▱</span><b>${esc(m.title)}</b></button>`).join(''):'<div class="empty-state">Você ainda não criou nenhum mangá.</div>';$$('[data-open-manga]').forEach(b=>b.onclick=()=>openManga(b.dataset.openManga));return}const items=profilePostsCache.filter(p=>tab==='videos'?p.media_type==='video':p.media_type!=='video');box.innerHTML=items.length?items.map(p=>p.media_type==='video'?`<button class="profile-grid-item" data-grid-post="${p.id}"><video src="${esc(p.media_url)}" muted preload="metadata"></video><span>▶</span></button>`:p.media_url?`<button class="profile-grid-item" data-grid-post="${p.id}"><img src="${esc(p.media_url)}" alt="Publicação"></button>`:`<button class="profile-grid-item text-grid" data-grid-post="${p.id}">${esc((p.body||'').slice(0,90))}</button>`).join(''):'<div class="empty-state">Nenhuma publicação nesta aba.</div>';$$('[data-grid-post]').forEach(b=>b.onclick=()=>openProfilePost(b.dataset.gridPost))}
async function openProfilePost(id){const p=profilePostsCache.find(x=>x.id===id);if(!p)return;nav('feed');setTimeout(()=>{const el=document.querySelector(`[data-post-id="${CSS.escape(id)}"]`);el?.scrollIntoView({behavior:'smooth',block:'center'})},120)}
function renderProfileStories(items){const own=items.slice(0,6);const box=$('#profileStories');box.innerHTML=`<button class="story-bubble" id="profileAddStory"><div class="story-ring"><span>＋</span></div><small>Novo</small></button>`+own.map(x=>`<button class="story-bubble" data-profile-story="${x.id}"><div class="story-ring">${x.media_url?`<img src="${esc(x.media_url)}">`:'<div class="story-placeholder">S</div>'}</div><small>Meus</small></button>`).join('');$('#profileAddStory').onclick=()=>openStoryComposer();$$('[data-profile-story]').forEach(b=>b.onclick=()=>{const st=items.find(x=>x.id===b.dataset.profileStory);if(st)openStory(st)})}

function chooseRole(){if(!user)return auth('login');$('#authContent').innerHTML=`<h2>Tipo de conta</h2><p class="muted">Escolha como você quer usar o LinkStory.</p><button class="role-btn" id="readerRole">📚 <b>Leitor</b><span>Descobrir, ler e acompanhar histórias.</span></button><button class="role-btn" id="creatorRole">✍️ <b>Criador</b><span>Publicar mangás, ideias e projetos.</span></button>`;$('#authModal').classList.remove('hidden');$('#readerRole').onclick=()=>saveRole('leitor');$('#creatorRole').onclick=()=>saveRole('criador')}
async function saveRole(role){const r=await sb.from('profiles').update({role}).eq('id',user.id);if(r.error)return toast(r.error.message);profile.role=role;closeModals();renderProfile();toast('Tipo de conta salvo.')}
function scorePost(p,likeCount=0){const t=taste();const words=String(p.body||'').toLowerCase();const tasteScore=Object.entries(t).reduce((s,[g,n])=>s+(words.includes(g)?n*2:0),0);const age=Math.max(0,(Date.now()-new Date(p.created_at).getTime())/3600000);const freshness=Math.max(0,48-age);return tasteScore+likeCount*0.35+freshness*0.08+(p.post_type==='video'?1:0)}
async function loadFeed(){const list=$('#feedList');list.innerHTML='<p class="feed-loading">Carregando Feed...</p>';let q=sb.from('posts').select('id,body,post_type,idea_title,author_id,created_at,media_url,media_type,thumbnail_url,profiles(display_name,username,avatar_url)').neq('post_type','story').order('created_at',{ascending:false}).limit(80);let followingIds=[];if(activeFeed==='following'){if(!user){list.innerHTML='<div class="empty-state">Entre para ver publicações de quem você segue.</div>';$('#storyStrip').innerHTML='';return}const f=await sb.from('follows').select('following_id').eq('follower_id',user.id);followingIds=(f.data||[]).map(x=>x.following_id);if(!followingIds.length){list.innerHTML='<div class="empty-state">Você ainda não segue ninguém.<br>Encontre criadores e comece a seguir.</div>';await loadStories();return}q=q.in('author_id',followingIds)}else{q=q.in('media_type',['image','video']);$('#storyStrip').innerHTML=''}const r=await q;if(r.error){list.innerHTML='<div class="empty-state">Não foi possível carregar o Feed agora.</div>';return}let posts=r.data||[];if(!posts.length){list.innerHTML='<div class="empty-state">O Feed ainda está vazio. Seja o primeiro a publicar.</div>';if(activeFeed==='following')await loadStories();return}const ids=posts.map(p=>p.id);const [likes,comments,myLikes,followRows]=await Promise.all([sb.from('post_likes').select('post_id').in('post_id',ids),sb.from('comments').select('post_id').in('post_id',ids),user?sb.from('post_likes').select('post_id').eq('user_id',user.id).in('post_id',ids):Promise.resolve({data:[]}),user?sb.from('follows').select('following_id').eq('follower_id',user.id):Promise.resolve({data:[]})]);const lc={};(likes.data||[]).forEach(x=>lc[x.post_id]=(lc[x.post_id]||0)+1);const cc={};(comments.data||[]).forEach(x=>cc[x.post_id]=(cc[x.post_id]||0)+1);const mine=new Set((myLikes.data||[]).map(x=>x.post_id));const following=new Set((followRows.data||[]).map(x=>x.following_id));if(activeFeed==='for_you')posts=posts.sort((a,b)=>scorePost(b,lc[b.id]||0)-scorePost(a,lc[a.id]||0));list.innerHTML=posts.map(p=>postHTML(p,lc[p.id]||0,cc[p.id]||0,mine.has(p.id),following.has(p.author_id))).join('');bindFeedActions();if(activeFeed==='following')await loadStories();$$('[data-video]').forEach(v=>{v.muted=true;v.playsInline=true;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.play().catch(()=>{});else e.target.pause()}),{threshold:.55});io.observe(v)})}
function bindFeedActions(){$$('[data-like]').forEach(b=>b.onclick=()=>toggleLike(b.dataset.like));$$('[data-comments]').forEach(b=>b.onclick=()=>openComments(b.dataset.comments));$$('[data-follow]').forEach(b=>b.onclick=()=>toggleFollow(b.dataset.follow));$$('[data-share]').forEach(b=>b.onclick=()=>sharePost(b.dataset.share));$$('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete))}
function postHTML(p,likes,comments,liked,isFollowing=false){const name=esc(p.profiles?.display_name||'Usuário'),handle=esc(p.profiles?.username||'usuario');const own=user?.id===p.author_id;const av=avatarHTML(p.profiles?.avatar_url,name,'avatar');let media='';if(p.media_type==='video'&&p.media_url)media=`<div class="video-wrap"><video data-video src="${esc(p.media_url)}" ${p.thumbnail_url?`poster="${esc(p.thumbnail_url)}"`:''} muted playsinline loop controls></video><div class="video-badge">PARA VOCÊ</div></div>`;else if(p.media_type==='image'&&p.media_url)media=`<img class="post-media" src="${esc(p.media_url)}" alt="Publicação de ${name}" loading="lazy">`;return `<article class="post ${p.media_type==='video'?'post-video':''}" data-post-id="${esc(p.id)}"><div class="post-user">${av}<div><b>${name} ${p.post_type==='idea'?'💡':''}</b><small>@${handle}.kx.mail</small></div><button class="more ${isFollowing?'following':''}" data-follow="${p.author_id}">${own?'Você':isFollowing?'Seguindo':'Seguir'}</button></div>${p.body?`<p>${esc(p.body)}</p>`:''}${media}${p.post_type==='idea'?'<div class="idea"><strong>💡 IDEIA ABERTA</strong><br><span>Uma ideia disponível para criadores interessados.</span></div>':''}<div class="actions"><button data-like="${p.id}" class="${liked?'liked':''}">${liked?'♥':'♡'} ${likes}</button><button data-comments="${p.id}">💬 ${comments}</button><button data-share="${p.id}">↗</button>${own?`<button data-delete="${p.id}" class="danger">Excluir</button>`:''}</div></article>`}
async function toggleLike(postId){if(!user)return auth('login');const existing=await sb.from('post_likes').select('post_id').eq('post_id',postId).eq('user_id',user.id).maybeSingle();if(existing.data){const r=await sb.from('post_likes').delete().eq('post_id',postId).eq('user_id',user.id);if(r.error)return toast(r.error.message)}else{const r=await sb.from('post_likes').insert({post_id:postId,user_id:user.id});if(r.error)return toast(r.error.message)}loadFeed()}
async function toggleFollow(target){if(!user)return auth('login');if(target===user.id)return toast('Você não pode seguir a si mesmo.');const e=await sb.from('follows').select('follower_id').eq('follower_id',user.id).eq('following_id',target).maybeSingle();if(e.data){await sb.from('follows').delete().eq('follower_id',user.id).eq('following_id',target);toast('Você deixou de seguir.')}else{const r=await sb.from('follows').insert({follower_id:user.id,following_id:target});if(r.error)return toast(r.error.message);toast('Agora você segue esse criador!')}loadFeed()}
async function openComments(postId){activeCommentPost=postId;$('#commentsList').innerHTML='<p class="feed-loading">Carregando comentários...</p>';$('#commentsModal').classList.remove('hidden');const r=await sb.from('comments').select('id,body,created_at,author_id,profiles(display_name,username,avatar_url)').eq('post_id',postId).order('created_at',{ascending:true});if(r.error)return $('#commentsList').innerHTML='<p class="muted">Erro ao carregar comentários.</p>';$('#commentsList').innerHTML=(r.data||[]).map(c=>`<div class="comment">${avatarHTML(c.profiles?.avatar_url,c.profiles?.display_name||'U','avatar')}<div><b>${esc(c.profiles?.display_name||'Usuário')}</b><small>@${esc(c.profiles?.username||'usuario')}.kx.mail</small><p>${esc(c.body)}</p></div></div>`).join('')||'<p class="muted">Ainda não há comentários.</p>'}
$('#commentBtn').onclick=async()=>{if(!user)return auth('login');const body=$('#commentText').value.trim();if(!body||!activeCommentPost)return;const r=await sb.from('comments').insert({post_id:activeCommentPost,author_id:user.id,body});if(r.error)return toast(r.error.message);$('#commentText').value='';await openComments(activeCommentPost);loadFeed();toast('Comentário publicado!')}
async function sharePost(id){const url=location.href.split('#')[0]+'#post-'+id;if(navigator.share){try{await navigator.share({title:'LinkStory',text:'Confira esta publicação no LinkStory',url})}catch{}}else{await navigator.clipboard?.writeText(url);toast('Link copiado!')}}
async function deletePost(id){if(!user||!confirm('Excluir esta publicação?'))return;const r=await sb.from('posts').delete().eq('id',id).eq('author_id',user.id);if(r.error)return toast(r.error.message);toast('Publicação excluída.');loadFeed();renderProfile()}
function openPost(){if(!user)return auth('login');$('#postModal').classList.remove('hidden')}
$('#quickPost').onclick=openPost;
$('#publishBtn').onclick=async()=>{if(!user)return auth('login');try{const body=$('#postText').value.trim();const file=$('#postMediaFile').files[0];if(!body&&!file)return toast('Escreva algo ou escolha uma foto.');let media_url=null,media_type=null;if(file){if(!file.type.startsWith('image/'))return toast('Nesta publicação use uma imagem.');media_url=await uploadFile(file,'posts');media_type='image'}const r=await sb.from('posts').insert({author_id:user.id,body:body||'',post_type:'post',media_url,media_type});if(r.error)throw r.error;$('#postText').value='';$('#postMediaFile').value='';closeModals();nav('feed');toast('Publicação criada!')}catch(e){toast(e.message||'Não foi possível publicar.')}};
$('#publishIdeaBtn').onclick=async()=>{if(!user)return auth('login');const title=$('#ideaTitle').value.trim(),text=$('#ideaText').value.trim();if(!title||!text)return toast('Preencha título e ideia.');const r=await sb.from('posts').insert({author_id:user.id,body:title+' — '+text,post_type:'idea',idea_title:title});if(r.error)return toast(r.error.message);$('#ideaTitle').value='';$('#ideaText').value='';closeModals();nav('feed');toast('Ideia publicada! 💡')};
$('#publishMangaBtn').onclick=async()=>{if(!requireCreator())return;try{const title=$('#mangaTitle').value.trim(),description=$('#mangaDescription').value.trim(),genres=$('#mangaGenres').value.trim(),coverFile=$('#mangaCoverFile').files[0],pages=[...$('#mangaPages').files];const age_rating=$('#mangaAge').value,format=$('#mangaFormat').value;const chapterNumber=Number($('#mangaChapterNumber').value||1);const chapterTitle=$('#mangaChapterTitle').value.trim()||`Capítulo ${chapterNumber}`;if(!title||!description||!genres)return toast('Preencha título, gênero e sinopse.');if(chapterNumber<1)return toast('Número de capítulo inválido.');let cover_url=null;if(coverFile){if(!coverFile.type.startsWith('image/'))return toast('A capa precisa ser uma imagem.');cover_url=await uploadFile(coverFile,'covers')}const r=await sb.from('mangas').insert({creator_id:user.id,title,description,genres,cover_url,status:'published',age_rating}).select('id').single();if(r.error)throw r.error;const mangaId=r.data.id;await saveChapterWithPages(mangaId,chapterNumber,chapterTitle,pages);resetMangaWizard();closeModals();await loadCatalog();await renderProfile();toast(`Obra publicada${pages.length?` com ${pages.length} páginas`:''}! 📖`)}catch(e){toast(e.message||'Não foi possível publicar o mangá.')}};
function resetMangaWizard(){$('#mangaTitle').value='';$('#mangaGenres').value='';$('#mangaDescription').value='';$('#mangaCoverFile').value='';$('#mangaPages').value='';$('#mangaChapterTitle').value='';$('#mangaChapterNumber').value='1';$('#mangaAge').value='L';$('#mangaFormat').value='vertical';$('#pagePreview').innerHTML='';$('#pageCount').textContent='0 páginas';showWizardStep(1)}
function showWizardStep(n){$$('.wizard-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));$$('.wizard-page').forEach(x=>x.classList.toggle('active',Number(x.dataset.page)===n));if(n===3)renderMangaReview()}
function moveFile(list,from,to){if(to<0||to>=list.length)return list;const a=[...list];const [item]=a.splice(from,1);a.splice(to,0,item);return a}
let mangaPageFiles=[];
function renderPagePreview(){const box=$('#pagePreview');$('#pageCount').textContent=`${mangaPageFiles.length} ${mangaPageFiles.length===1?'página':'páginas'}`;box.innerHTML=mangaPageFiles.map((f,i)=>`<div class="page-thumb"><img src="${URL.createObjectURL(f)}" alt="Página ${i+1}"><div class="thumb-actions"><button data-page-up="${i}">↑</button><button data-page-down="${i}">↓</button></div></div>`).join('');$$('[data-page-up]').forEach(b=>b.onclick=()=>{mangaPageFiles=moveFile(mangaPageFiles,Number(b.dataset.pageUp),Number(b.dataset.pageUp)-1);renderPagePreview()});$$('[data-page-down]').forEach(b=>b.onclick=()=>{mangaPageFiles=moveFile(mangaPageFiles,Number(b.dataset.pageDown),Number(b.dataset.pageDown)+1);renderPagePreview()})}
$('#mangaPages').onchange=e=>{mangaPageFiles=[...e.target.files];renderPagePreview()};$('#mangaChapterNumber').oninput=e=>{const n=Math.max(1,Number(e.target.value||1));e.target.value=n;$('#chapterNumberHelp').textContent=n===1?'Este é o primeiro capítulo da obra.':`Este será o capítulo ${n} da obra.`};$$('.wizard-next').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.next);if(n===2){if(!$('#mangaTitle').value.trim()||!$('#mangaDescription').value.trim()||!$('#mangaGenres').value.trim())return toast('Complete os dados da obra primeiro.')}if(n===3&&!mangaPageFiles.length)return toast('Selecione pelo menos uma página para o primeiro capítulo.');showWizardStep(n)});$$('.wizard-back').forEach(b=>b.onclick=()=>showWizardStep(Number(b.dataset.back)));$$('.wizard-step').forEach(b=>b.onclick=()=>showWizardStep(Number(b.dataset.step)));
function renderMangaReview(){const title=$('#mangaTitle').value.trim(),genres=$('#mangaGenres').value.trim(),desc=$('#mangaDescription').value.trim(),cover=$('#mangaCoverFile').files[0],chapter=$('#mangaChapterTitle').value.trim()||`Capítulo ${$('#mangaChapterNumber').value||1}`;const url=cover?URL.createObjectURL(cover):'';$('#mangaReview').innerHTML=`<div class="review-card"><div class="review-cover">${url?`<img src="${url}">`:'<span>LS</span>'}</div><div class="review-meta"><b>${esc(title)}</b><p>${esc(genres)}</p><p>${esc(desc)}</p><p><strong>${esc(chapter)}</strong> · ${mangaPageFiles.length} páginas · ${esc($('#mangaFormat').value)}</p></div></div><div class="wizard-tip"><b>Kiro:</b> depois da publicação, a obra continua no seu painel. Você poderá adicionar o próximo capítulo sem criar outra obra.</div>`}
async function saveChapterWithPages(mangaId,number,title,files){const ch=await sb.from('manga_chapters').insert({manga_id:mangaId,chapter_number:number,title}).select('id').single();if(ch.error)throw ch.error;for(let i=0;i<files.length;i++){const f=files[i];if(!f.type.startsWith('image/'))continue;const url=await uploadFile(f,'manga-pages');const pr=await sb.from('manga_pages').insert({chapter_id:ch.data.id,page_number:i+1,image_url:url});if(pr.error)throw pr.error}}
async function renderCreatorMangas(list=null){if(!user)return;if(!list){const r=await sb.from('mangas').select('id,title,description,cover_url,genres,created_at').eq('creator_id',user.id).order('created_at',{ascending:false});list=r.data||[]}const box=$('#creatorMangaList');if(!list.length){box.innerHTML='<div class="empty-state">Você ainda não criou nenhum mangá.</div>';return}box.innerHTML=list.map(m=>`<div class="manager-card"><div class="manager-cover">${m.cover_url?`<img src="${esc(m.cover_url)}">`:esc((m.title||'M').slice(0,1))}</div><div><h3>${esc(m.title)}</h3><p>${esc(m.genres||'Mangá')}</p></div><button class="outline small" data-add-chapter="${m.id}" data-manga-title="${esc(m.title)}">+ capítulo</button></div>`).join('');$$('[data-add-chapter]').forEach(b=>b.onclick=()=>openAddChapter(b.dataset.addChapter,b.dataset.mangaTitle))}
async function openMangaManager(){if(!requireCreator())return;const r=await sb.from('mangas').select('id,title,description,cover_url,genres,created_at').eq('creator_id',user.id).order('created_at',{ascending:false});const list=r.data||[];$('#mangaManagerList').innerHTML=list.length?list.map(m=>`<div class="manager-card"><div class="manager-cover">${m.cover_url?`<img src="${esc(m.cover_url)}">`:esc((m.title||'M').slice(0,1))}</div><div><h3>${esc(m.title)}</h3><p>${esc(m.genres||'Mangá')}</p></div><button class="outline small" data-manager-add="${m.id}" data-manager-title="${esc(m.title)}">+ capítulo</button></div>`).join(''):'<div class="empty-state">Nenhum mangá criado ainda.</div>';$$('[data-manager-add]').forEach(b=>b.onclick=()=>openAddChapter(b.dataset.managerAdd,b.dataset.managerTitle));$('#mangaManagerModal').classList.remove('hidden')}
async function openAddChapter(mangaId,title){if(!requireCreator())return;$('#chapterMangaId').value=mangaId;$('#chapterModalTitle').textContent=`Adicionar capítulo — ${title}`;const r=await sb.from('manga_chapters').select('chapter_number').eq('manga_id',mangaId).order('chapter_number',{ascending:false}).limit(1);$('#newChapterNumber').value=Number(r.data?.[0]?.chapter_number||0)+1;$('#newChapterTitle').value='';$('#newChapterPages').value='';$('#newChapterPreview').innerHTML='';$('#mangaManagerModal').classList.add('hidden');$('#chapterModal').classList.remove('hidden')}
$('#newChapterPages').onchange=e=>{$('#newChapterPreview').innerHTML=[...e.target.files].map((f,i)=>`<div class="page-thumb"><img src="${URL.createObjectURL(f)}" alt="Página ${i+1}"></div>`).join('')};$('#publishChapterBtn').onclick=async()=>{if(!requireCreator())return;try{const mangaId=$('#chapterMangaId').value,number=Number($('#newChapterNumber').value),title=$('#newChapterTitle').value.trim()||`Capítulo ${number}`,files=[...$('#newChapterPages').files];if(!mangaId||number<1||!files.length)return toast('Informe o capítulo e selecione as páginas.');const exists=await sb.from('manga_chapters').select('id').eq('manga_id',mangaId).eq('chapter_number',number).maybeSingle();if(exists.data)return toast('Esse número de capítulo já existe.');await saveChapterWithPages(mangaId,number,title,files);closeModals();await renderProfile();toast(`Capítulo ${number} publicado! 📖`)}catch(e){toast(e.message||'Não foi possível publicar o capítulo.')}};
$('#manageMangasBtn').onclick=openMangaManager;$('#profileEditTop').onclick=()=>user?openEditProfile():auth('login');$('#profileAvatar').onclick=()=>user?openEditProfile():auth('login');function openStoryComposer(){if(!user)return auth('login');storySelectedFile=null;$('#storyText').value='';$('#storyPreview').removeAttribute('src');$('#storyStart').classList.remove('hidden');$('#storyEditor').classList.add('hidden');$('#storyModal').classList.remove('hidden')}$('#profileStoryBtn').onclick=openStoryComposer;
async function loadStories(){const box=$('#storyStrip');if(activeFeed!=='following'){box.innerHTML='';return}const since=new Date(Date.now()-86400000).toISOString();let allowed=[];if(user){const f=await sb.from('follows').select('following_id').eq('follower_id',user.id);allowed=(f.data||[]).map(x=>x.following_id);allowed.push(user.id)}else{box.innerHTML='';return}const r=await sb.from('posts').select('id,body,author_id,media_url,media_type,created_at,profiles(display_name,username,avatar_url)').eq('post_type','story').gte('created_at',since).in('author_id',allowed).order('created_at',{ascending:false}).limit(40);const rows=r.data||[];const grouped=new Map();rows.forEach(x=>{if(!grouped.has(x.author_id))grouped.set(x.author_id,x)});const all=[...grouped.values()];if(user&&!grouped.has(user.id))all.unshift({id:'new',author_id:user.id,own:true,profiles:{display_name:profile?.display_name||'Você',username:profile?.username||'usuario',avatar_url:profile?.avatar_url}});box.innerHTML=all.length?all.map(x=>`<button class="story-item ${x.own?'story-add':''}" data-story="${x.id}"><div class="story-ring">${x.own&&!x.media_url?'<span>＋</span>':x.profiles?.avatar_url?`<img src="${esc(x.profiles.avatar_url)}">`:`<div class="story-placeholder">${esc((x.profiles?.display_name||'U').slice(0,1))}</div>`}</div><small>${x.own?'Seu story':esc(x.profiles?.display_name||'Usuário')}</small></button>`).join(''):'<div class="empty-state story-empty">Nenhum story das pessoas que você segue.</div>';$$('[data-story]').forEach(b=>b.onclick=()=>{if(b.dataset.story==='new')return openStoryComposer();const st=rows.find(x=>x.id===b.dataset.story);if(st)openStory(st)})}

function renderProfileStories(items){const box=$('#profileStories');const own=items.filter(x=>x.post_type==='story').slice(0,6);box.innerHTML=`<button class="story-bubble" id="profileAddStory"><div class="story-ring"><span>＋</span></div><small>Novo</small></button>`+own.map(x=>`<button class="story-bubble"><div class="story-ring">${x.media_url?`<img src="${esc(x.media_url)}">`:'<div class="story-placeholder">S</div>'}</div><small>Meus</small></button>`).join('');$('#profileAddStory').onclick=()=>$('#storyModal').classList.remove('hidden')}
function openStory(st){$('#storyViewer').innerHTML=`<div class="story-full">${st.media_url?`<img src="${esc(st.media_url)}" alt="Story">`:''}<div class="story-full-caption">${esc(st.body||'')}</div><small>${new Date(st.created_at).toLocaleString('pt-BR')}</small></div>`;$('#storyViewerModal').classList.remove('hidden')}
let storySelectedFile=null;function openStoryEditor(file){if(!file||!file.type.startsWith('image/'))return toast('Escolha uma imagem válida.');storySelectedFile=file;$('#storyPreview').src=URL.createObjectURL(file);$('#storyStart').classList.add('hidden');$('#storyEditor').classList.remove('hidden')}$('#storyCameraBtn').onclick=()=>$('#storyCameraFile').click();$('#storyGalleryBtn').onclick=()=>$('#storyGalleryFile').click();$('#storyCameraFile').onchange=e=>openStoryEditor(e.target.files[0]);$('#storyGalleryFile').onchange=e=>openStoryEditor(e.target.files[0]);$('#storyChangeBtn').onclick=()=>{$('#storyStart').classList.remove('hidden');$('#storyEditor').classList.add('hidden')};$('#publishStoryBtn').onclick=async()=>{if(!user)return auth('login');try{const file=storySelectedFile,body=$('#storyText').value.trim();if(!file)return toast('Escolha uma foto para o story.');const media_url=await uploadFile(file,'stories');const r=await sb.from('posts').insert({author_id:user.id,body:body||'',post_type:'story',media_url,media_type:'image'});if(r.error)throw r.error;storySelectedFile=null;$('#storyCameraFile').value='';$('#storyGalleryFile').value='';$('#storyText').value='';closeModals();await loadStories();await renderProfile();toast('Story publicado por 24h!')}catch(e){toast(e.message||'Não foi possível publicar o story.')}};
const _loadFeed=loadFeed;loadFeed=async function(){await _loadFeed();await loadStories()};

$('#publishVideoBtn').onclick=async()=>{if(!user)return auth('login');try{const body=$('#videoText').value.trim(),file=$('#videoFile').files[0];if(!file||!file.type.startsWith('video/'))return toast('Escolha um vídeo.');if(file.size>50*1024*1024)return toast('O vídeo precisa ter até 50 MB.');const media_url=await uploadFile(file,'videos');const r=await sb.from('posts').insert({author_id:user.id,body,post_type:'video',media_url,media_type:'video'});if(r.error)throw r.error;$('#videoText').value='';$('#videoFile').value='';closeModals();nav('feed');toast('Vídeo publicado no Feed! 🎬')}catch(e){toast(e.message||'Não foi possível publicar o vídeo.')}};
$('#mangaCreate').onclick=()=>{if(!requireCreator())return;$('#mangaModal').classList.remove('hidden')};$('#videoCreate').onclick=()=>{if(!user)return auth('login');$('#videoModal').classList.remove('hidden')};$('#ideaCreate').onclick=()=>{if(!user)return auth('login');$('#ideaModal').classList.remove('hidden')};
$('#authBtn').onclick=()=>user?logout():auth('login');$('#registerBtn').onclick=()=>auth('register');$('#readBtn').onclick=()=>nav('feed');$('#feedRefresh').onclick=()=>loadFeed();
$$('[data-feed]').forEach(b=>b.onclick=()=>{activeFeed=b.dataset.feed;$$('[data-feed]').forEach(x=>x.classList.toggle('active',x===b));loadFeed()});
$$('[data-browse]').forEach(b=>b.onclick=()=>{nav('feed');toast('Catálogo aberto no Feed por enquanto.')});
$('#searchBtn').onclick=()=>{$('#searchModal').classList.remove('hidden');$('#searchInput').focus();renderSearch('')};$('#searchInput').oninput=e=>renderSearch(e.target.value);
function renderSearch(q){const term=q.trim().toLowerCase();const ms=demoMangas.filter(m=>!term||[m.title,m.author,m.genres].join(' ').toLowerCase().includes(term));$('#searchResults').innerHTML=ms.map(m=>`<button class="search-item" data-search-manga="${m.id}"><div class="mini-cover cover ${m.cover}">${esc(m.title[0])}</div><div><b>${esc(m.title)}</b><small>${esc(m.author)} · ${esc(m.genres)}</small></div></button>`).join('')||'<p class="muted">Nada encontrado.</p>';$$('[data-search-manga]').forEach(b=>b.onclick=()=>{closeModals();openManga(b.dataset.searchManga)})}
async function loadNotifications(){const box=$('#noticeList');if(!user){box.innerHTML='<div class="empty-state">Entre na sua conta para ver seus avisos.</div>';return}const r=await sb.from('notifications').select('id,type,post_id,read_at,created_at,actor_id').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30);if(r.error){box.innerHTML='<div class="empty-state">Não foi possível carregar os avisos.</div>';return}box.innerHTML=(r.data||[]).map(n=>`<div class="notice ${n.read_at?'':'unread'}"><div class="avatar gold">${n.type==='like'?'♥':n.type==='comment'?'💬':n.type==='follow'?'＋':'•'}</div><p>${noticeText(n.type)}<small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></p></div>`).join('')||'<div class="empty-state">Nenhum aviso ainda.</div>'}
function noticeText(type){return ({like:'Alguém curtiu sua publicação.',comment:'Alguém comentou na sua publicação.',follow:'Alguém começou a seguir você.'}[type]||'Você tem uma nova atividade no LinkStory.')}
$('#readNotices').onclick=async()=>{if(!user)return auth('login');await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);loadNotifications();toast('Avisos marcados como lidos.')};
sb.auth.onAuthStateChange(async(_event,session)=>{user=session?.user||null;await loadProfile();renderProfile();if($('#feed').classList.contains('active'))loadFeed()});
(async()=>{const s=await sb.auth.getSession();user=s.data.session?.user||null;await loadProfile();applyRoleUI();await loadCatalog();renderProfile();loadFeed()})();

$$('[data-profile-tab]').forEach(b=>b.onclick=()=>renderProfileTab(b.dataset.profileTab));
let cropSourceFile=null,cropObjectUrl=null;
function openAvatarCrop(){const f=$('#editAvatarFile').files[0];if(!f){toast('Escolha uma foto primeiro.');return}cropSourceFile=f;if(cropObjectUrl)URL.revokeObjectURL(cropObjectUrl);cropObjectUrl=URL.createObjectURL(f);$('#cropImage').src=cropObjectUrl;$('#cropZoom').value=1;$('#cropX').value=50;$('#cropY').value=50;updateCropPreview();$('#avatarCropModal').classList.remove('hidden')}
function updateCropPreview(){const img=$('#cropImage');if(!img)return;img.style.transform=`scale(${$('#cropZoom').value})`;img.style.objectPosition=`${$('#cropX').value}% ${$('#cropY').value}%`}
$('#avatarCropOpen').onclick=openAvatarCrop;$('#editAvatarFile').onchange=()=>{if($('#editAvatarFile').files[0])openAvatarCrop()};['cropZoom','cropX','cropY'].forEach(id=>$('#'+id).oninput=updateCropPreview);
async function cropAvatarToBlob(file,zoom,x,y){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const size=640,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');const scale=Math.max(size/img.width,size/img.height)*zoom;const dw=img.width*scale,dh=img.height*scale;const maxX=Math.max(0,dw-size),maxY=Math.max(0,dh-size);const dx=-(x/100)*maxX,dy=-(y/100)*maxY;ctx.fillStyle='#111';ctx.fillRect(0,0,size,size);ctx.drawImage(img,dx,dy,dw,dh);canvas.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve(blob):reject(new Error('Não foi possível recortar a foto.'))},'image/jpeg',.92)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível ler a foto.'))};img.src=url})}
$('#cropConfirmBtn').onclick=async()=>{if(!cropSourceFile)return;try{const blob=await cropAvatarToBlob(cropSourceFile,Number($('#cropZoom').value),Number($('#cropX').value),Number($('#cropY').value));const cropped=new File([blob],'avatar.jpg',{type:'image/jpeg'});const dt=new DataTransfer();dt.items.add(cropped);$('#editAvatarFile').files=dt.files;$('#avatarCropThumb').innerHTML=`<img src="${URL.createObjectURL(blob)}" alt="Prévia">`;closeModals();$('#editProfileModal').classList.remove('hidden');toast('Enquadramento aplicado. Clique em Salvar perfil.')}catch(e){toast(e.message)}};
