const mangas=[{title:'Tuketon',author:'Kairox Studio',genre:'Aventura · Fantasia',tag:'TK',desc:'Um mundo de reinos, selos e energia INKRA.'},{title:'Horizonte',author:'L. Santos',genre:'Ação · Mistério',tag:'HZ',desc:'Uma jornada começa quando o horizonte deixa de ser o fim.'},{title:'Eclipse',author:'Maya',genre:'Drama · Fantasia',tag:'EC',desc:'Quando a noite cobre tudo, algumas verdades aparecem.'},{title:'Última Lua',author:'Kairox',genre:'Ação · Drama',tag:'UL',desc:'O último brilho antes do silêncio.'},{title:'Áurea',author:'Niko',genre:'Aventura · Shonen',tag:'AU',desc:'Um reino dourado guarda um segredo.'},{title:'Depois da Chuva',author:'Lia',genre:'Romance · Slice of life',tag:'DC',desc:'Algumas histórias começam quando a chuva termina.'}];
const $=s=>document.querySelector(s);
function card(m,i){return `<button class="manga-card" data-index="${i}"><div class="cover"><span>${m.tag}</span></div><h3>${m.title}</h3><p>${m.genre}</p></button>`}
function render(){$('#trending').innerHTML=mangas.slice(0,5).map(card).join('');$('#newManga').innerHTML=mangas.slice(2,6).map(m=>card(m,mangas.indexOf(m))).join('');document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.index)))}
function openDetail(i){const m=mangas[i];$('#detailContent').innerHTML=`<div class="cover detail-cover"><span>${m.tag}</span></div><span class="eyebrow">MANGÁ</span><h2>${m.title}</h2><p class="detail-meta"><b>${m.author}</b><br>${m.genre}<br><br>${m.desc}</p><button class="primary" id="readNow">Começar a ler</button>`;$('#detailDialog').showModal();$('#readNow').onclick=()=>location.href='reader.html?manga='+encodeURIComponent(m.title)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2400)}
function openSearch(){const d=$('#searchDialog');d.showModal();$('#searchInput').value='';$('#searchResults').innerHTML='';setTimeout(()=>$('#searchInput').focus(),50)}
$('#openSearch').onclick=openSearch;
$('#searchInput').oninput=e=>{const q=e.target.value.trim().toLowerCase();const r=mangas.filter(m=>(m.title+' '+m.author+' '+m.genre).toLowerCase().includes(q));$('#searchResults').innerHTML=q?(r.length?r.map(m=>`<button class="result" data-index="${mangas.indexOf(m)}"><b>${m.title}</b><br><small>${m.author} · ${m.genre}</small></button>`).join(''):'<p class="detail-meta">Nenhum mangá encontrado.</p>'):'';document.querySelectorAll('.result').forEach(b=>b.onclick=()=>{d.close();openDetail(Number(b.dataset.index))})};
['#loginButton','#createButton','#bannerCreate'].forEach(id=>$(id).onclick=()=>toast(id==='#loginButton'?'Login entra na próxima etapa.':'Publicação entra na próxima etapa.'));
render();
