(()=>{
  if(document.getElementById('lsBottomNav'))return;
  const css=`#lsBottomNav{position:fixed;left:50%;bottom:12px;transform:translateX(-50%);width:min(430px,calc(100% - 24px));height:64px;background:rgba(255,255,255,.97);border:1px solid #dbe5ef;border-radius:20px;box-shadow:0 12px 35px rgba(16,32,51,.14);display:grid;grid-template-columns:repeat(3,1fr);z-index:1000;backdrop-filter:blur(14px)}#lsBottomNav a{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;color:#66788d;text-decoration:none;font:800 10px/1 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#lsBottomNav a.active{color:#0b72e7}#lsBottomNav .ls-icon{width:23px;height:23px;display:grid;place-items:center;font-size:19px;line-height:1}#lsBottomNav a.active .ls-icon{transform:translateY(-1px}body{padding-bottom:92px!important}.ls-global-menu-btn{width:42px;height:42px;border:1px solid #dbe5ef;border-radius:50%;background:#fff;color:#102033;display:flex;align-items:center;justify-content:center;padding:0;font-size:18px;line-height:1;margin-left:auto}.ls-global-menu-btn:hover{border-color:#0b72e7;color:#0b72e7}.ls-menu-dialog{width:min(100%,520px);height:100dvh;max-height:none;margin:0 0 0 auto;border:0;padding:0;background:#fff;color:#102033}.ls-menu-wrap{height:100%;padding:24px 20px;overflow:auto}.ls-menu-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:18px;border-bottom:1px solid #dbe5ef}.ls-menu-head strong{color:#0b72e7;letter-spacing:3px;font:950 18px/1 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ls-menu-close{border:0;background:none;font-size:34px;line-height:1;color:#102033}.ls-menu-links{display:grid;margin-top:8px}.ls-menu-links a{display:flex;align-items:center;justify-content:space-between;padding:16px 2px;border-bottom:1px solid #dbe5ef;text-decoration:none;color:#102033;font:850 16px/1.2 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ls-menu-links a:last-child{color:#0b72e7}.ls-menu-links span{color:#7a8da0;font-size:22px}@media(min-width:801px){#lsBottomNav{bottom:18px}.ls-menu-dialog{border-radius:20px;margin:16px;max-height:calc(100dvh - 32px);height:auto}.ls-menu-wrap{min-height:520px}}`;
  const st=document.createElement('style');st.id='lsGlobalNavStyle';st.textContent=css;document.head.appendChild(st);
  const path=location.pathname.split('/').pop()||'index.html';
  const active=path==='explore.html'?'explore':path==='library.html'?'library':'home';
  const nav=document.createElement('nav');nav.id='lsBottomNav';nav.setAttribute('aria-label','Navegação principal');
  nav.innerHTML=`<a href="index.html" class="${active==='home'?'active':''}"><span class="ls-icon">⌂</span><span>Início</span></a><a href="explore.html" class="${active==='explore'?'active':''}"><span class="ls-icon">◉</span><span>Explorar</span></a><a href="library.html" class="${active==='library'?'active':''}"><span class="ls-icon">▣</span><span>Biblioteca</span></a>`;
  document.body.appendChild(nav);
  let menu=document.getElementById('menuDialog');let opener=document.getElementById('openMenu');
  if(!menu){
    menu=document.createElement('dialog');menu.id='lsMenu';menu.className='ls-menu-dialog';
    menu.innerHTML=`<div class="ls-menu-wrap"><div class="ls-menu-head"><strong>LINKSTORY</strong><button class="ls-menu-close" aria-label="Fechar">×</button></div><nav class="ls-menu-links"><a href="profile.html">Perfil <span>›</span></a><a href="studio.html">Meu Estúdio <span>›</span></a><a href="publish.html">Publicar mangá <span>›</span></a><a href="settings.html">Configurações <span>›</span></a><a href="login.html">Entrar <span>›</span></a></nav></div>`;
    document.body.appendChild(menu);
    opener=document.createElement('button');opener.id='lsGlobalMenuButton';opener.className='ls-global-menu-btn';opener.setAttribute('aria-label','Abrir menu');opener.innerHTML='☰';
    const header=document.querySelector('.topbar,.top,.header');
    if(header)header.appendChild(opener);else{opener.style.position='fixed';opener.style.top='14px';opener.style.right='14px';opener.style.zIndex='1001';document.body.appendChild(opener)}
  }
  if(opener&&!opener.dataset.lsBound){opener.dataset.lsBound='1';opener.addEventListener('click',()=>menu.showModal())}
  const close=menu.querySelector('.ls-menu-close,.dialog-close,.close');if(close&&!close.dataset.lsBound){close.dataset.lsBound='1';close.addEventListener('click',()=>menu.close())}
  if(!menu.dataset.lsBound){menu.dataset.lsBound='1';menu.addEventListener('click',e=>{if(e.target===menu)menu.close()})}
})();