/* LinkStory V5 — profile media ownership + feed redesign */
(()=>{
 const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
 const toastLS=m=>typeof window.toast==='function'?window.toast(m):alert(m);
 async function removeAvatar(e){e.stopPropagation();if(!window.user||!window.sb)return;if(!confirm('Remover sua foto de perfil?'))return;const r=await window.sb.from('profiles').update({avatar_url:null}).eq('id',window.user.id);if(r.error)return toastLS('Não foi possível remover a foto.');if(window.loadProfile)await window.loadProfile();if(window.renderProfile)window.renderProfile();toastLS('Foto de perfil removida.')}
 async function removePost(e){e.preventDefault();e.stopPropagation();const el=e.currentTarget.parentElement,id=el.dataset.postId||el.dataset.id||el.dataset.profilePost;if(!id||!window.user||!window.sb)return toastLS('Publicação sem identificação.');if(!confirm('Remover esta publicação do seu perfil?'))return;const r=await window.sb.from('posts').delete().eq('id',id).eq('user_id',window.user.id);if(r.error)return toastLS('Não foi possível remover: '+r.error.message);el.remove();toastLS('Publicação removida.');if(window.renderProfile)window.renderProfile()}
 function controls(){const av=$('#profileAvatar');if(av&&!av.parentElement.querySelector('.avatar-remove-btn')){const b=document.createElement('button');b.className='avatar-remove-btn';b.type='button';b.textContent='Remover foto de perfil';b.onclick=removeAvatar;av.parentElement.appendChild(b)}$$('.profile-grid-item').forEach(el=>{if(el.querySelector('.profile-remove-btn'))return;const id=el.dataset.postId||el.dataset.id||el.dataset.profilePost;if(!id)return;const b=document.createElement('button');b.className='profile-remove-btn';b.type='button';b.textContent='×';b.title='Remover publicação';b.onclick=removePost;el.appendChild(b)})}
 new MutationObserver(controls).observe(document.body,{childList:true,subtree:true});setTimeout(controls,300);
 document.addEventListener('click',e=>{const item=e.target.closest('.profile-grid-item');if(item&&!e.target.closest('.profile-remove-btn')){const id=item.dataset.postId||item.dataset.id||item.dataset.profilePost;if(id){e.preventDefault();e.stopImmediatePropagation();if(window.openOwnProfilePost)window.openOwnProfilePost(id,item);else if(window.openPost)window.openPost(id)}}},true);
 const st=document.createElement('style');st.textContent='.avatar-remove-btn{display:block;margin:8px auto;border:1px solid #333;background:#101010;color:#aaa;border-radius:999px;padding:7px 11px;font-size:10px}.profile-grid-item{cursor:pointer}.profile-remove-btn{position:absolute!important;right:7px;top:7px;z-index:9;width:28px;height:28px;border-radius:50%;border:1px solid #666!important;background:#090909e8!important;color:#fff!important;font-size:20px!important;padding:0!important}.profile-grid-item{position:relative}#feed{background:#050505}.feed-v5-head{position:sticky;top:62px;z-index:11;padding:13px 18px;background:#070707ee;backdrop-filter:blur(18px);border-bottom:1px solid #222;display:flex;align-items:center;justify-content:space-between}.feed-v5-head h1{margin:0;font-size:25px;letter-spacing:-1px}.feed-v5-head p{margin:3px 0 0;color:#666;font-size:10px}.feed-v5-tabs{display:flex;gap:5px}.feed-v5-tabs button{border:1px solid #292929;background:#0d0d0d;color:#777;border-radius:999px;padding:7px 11px;font-size:10px;font-weight:900}.feed-v5-tabs button.active{background:#eee;color:#080808}.feed-v5-card{margin:10px 12px;background:#0b0b0b;border:1px solid #222;border-radius:18px;overflow:hidden;box-shadow:0 8px 28px #000}.feed-v5-card .post{margin:0!important;border:0!important;background:transparent!important;padding:14px!important}.feed-v5-card .actions{border-top:1px solid #1d1d1d;margin-top:12px;padding-top:8px}';document.head.appendChild(st);
 function redesign(){const feed=$('#feed');if(!feed||feed.dataset.v5)return;feed.dataset.v5='1';const observer=new MutationObserver(()=>{const posts=[...feed.querySelectorAll('.post')];if(!posts.length)return;let wrap=feed.querySelector('.feed-v5');if(!wrap){wrap=document.createElement('div');wrap.className='feed-v5';const h=document.createElement('div');h.className='feed-v5-head';h.innerHTML='<div><h1>FY</h1><p>Histórias da comunidade LinkStory</p></div><div class="feed-v5-tabs"><button class="active" type="button">Para você</button><button type="button">Seguindo</button></div>';feed.append(h,wrap)}posts.forEach(p=>{if(p.closest('.feed-v5-card'))return;const c=document.createElement('article');c.className='feed-v5-card';p.parentNode.insertBefore(c,p);c.appendChild(p)})});observer.observe(feed,{childList:true,subtree:true})}redesign();
})();
